# Generated by Django 2.2 on 2019-05-01 03:57

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='myfield',
            field=markdownx.models.MarkdownxField(default='test'),
        ),
    ]
