# Generated by Django 2.2 on 2019-05-01 05:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_myfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='myfield',
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
